### ISSUE TITLE
unable to do rpc authentication 

### ISSUE THREAD

**Issue by powerunlimited** [kstep/ajenti-transmission#6]
installed perfectly, just a small problem
whenever i  have  `rpc authentication` enabled in transmission it complains about an invalid authentication and jumps back to the config panel. 
poked around and couldn't find where to input my credentials so i assume that some how this plugin doesn't support that? is it  possible to implement this feature ?

**Comment by ilMike42** [comment]
I'm unable to authenticate, too.

**Comment by kstep** [comment]
Yes, the plugin doesn't support authorization.

I don't use Ajenti anymore, so I'm not interested in developing the plugin further.
If you need it, you are very welcome to implement whatever feature you want.
